global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ecommerce-dashboard'
    static_configs:
      - targets: ['localhost:2710']
    metrics_path: '/api/metrics'
